### PR TITLE
Update normalize.css to 4.0.0

### PR DESCRIPTION
**Pull request by oskarrough**
This updates normalize to the 4.0.0 release.

### CODE REVIEW

**Comment by AntonTrollback** [comment]
Wait for 4.0.1? Looks like they have a few changes on the way

**Comment by simonsmith** [comment]
Yeah? Can maybe merge this then and publish whenever the patch appears

**Comment by giuseppeg** [comment]
We need to patch `base.css` afaik there is at least one thing to fix that is removing the reset for `input[type="search"]`.

Also this has to be a major release.

**Comment by AntonTrollback** [comment]
Can be removed from Button:
```
.Button::-moz-focus-inner {
  border: 0;
  padding: 0;
}
```

**Comment by simonsmith** [comment]
Agreed about testing. I can look over the test page in Browserstac

**Comment by simonsmith** [comment]
Closed in favour of https://github.com/suitcss/base/pull/32

@oskarrough Added your commit to the new PR so I could add some additional changes

**Comment by oskarrough** [comment]
Thanks!

**Pull request closed without merging**
